### ISSUE TITLE
Save issue

### ISSUE THREAD

**Issue by heqichen** [taweili/openblocks#1] opened 2011-08-21 16:23 UTC
The SaveCode get from WrokspaceController contains illegal string

**Comment by taweili** [comment] 2011-08-22 01:37
The saving problem is caused by not being able to locate "/edu/mit/blocks/codeblocks/codeblocks.xsd". Issue fixed with new getResource(). Let me know if it works for you.

**Closed as completed** 2011-08-22 02:04 UTC
